import validate from "@/constant/constValidate.js";

export let inputSignupInformations = [
    {
        label: "نام کاربری",
        id: "username",
        name: "username",
        type: "text",
        validate: validate.validateUsername,
        icon: "icon-user",
    },
    {
        label: "رمز عبور",
        id: "password",
        name: "password",
        type: "password",
        autocomplete: "off",
        validate: validate.validatePassword,
        strong: true,
        icon: "icon-key",
    },
    {
        label: "کدملی",
        id: "nationalCode",
        name: "nationalCode",
        type: "text",
        validate: validate.validateId,
        icon: "icon-fingerprint",
    },
    {
        label: "عنوان شغلی",
        id: "jobTitle",
        name: "jobTitle",
        type: "text",
        validate: validate.validateJobTitle,
        icon: "icon-portfolio",
    },
    {
        label: "مهارت شغلی",
        id: "jobSkills",
        name: "jobSkills",
        type: "text",
        validate: validate.validateJobSkill,
        icon: "icon-skills",
    },
    {
        label: "نام و نام خانوادگی",
        id: "fullName",
        name: "fullName",
        type: "text",
        validate: validate.validateFullName,
        icon: "icon-user",
    },
    {
        label: "مرد",
        id: "0",
        name: "gender",
        type: "radio",
        description: "جنسیت",
        icon: "",
    },
    {
        label: "زن",
        id: "1",
        name: "gender",
        type: "radio",
        icon: "",
    },
    {
        label: "تحصیلات",
        id: "education",
        name: "education",
        type: "text",
        validate: validate.validateEducation,
        icon: "icon-open-book",
    },
    {
        label: "شماره همراه",
        id: "phone",
        name: "phone",
        type: "text",
        validate: validate.validatePhone,
        icon: "icon-phone",
    },
    {
        label: "ایمیل",
        id: "email",
        name: "email",
        type: "email",
        validate: validate.validateEmail,
        icon: "icon-email",
    },
]

export let inputLoginInformations = [
    {
        label: "نام کاربری",
        id: "username",
        name: "username",
        type: "text",
        autocomplete: "on",
        validate: validate.validateUsername,
        icon: "icon-user",
    },
    {
        label: "رمز عبور",
        id: "password",
        name: "password",
        type: "password",
        autocomplete: "off",
        validate: validate.validateLoginPassword,
        icon: "icon-key",
    },
]

export let inputProfileInformations = [
    {
        label: "نام کاربری",
        id: "username",
        name: "username",
        type: "text",
        validate: validate.validateUsername,
        disabled: true,
        icon: "icon-user",
    },
    {
        label: "رمز عبور",
        id: "password",
        name: "password",
        type: "password",
        autocomplete: "off",
        validate: validate.validatePassword,
        strong: true,
        icon: "icon-key",
    },
    {
        label: "کدملی",
        id: "nationalCode",
        name: "nationalCode",
        type: "text",
        validate: validate.validateId,
        icon: "icon-fingerprint",
    },
    {
        label: "عنوان شغلی",
        id: "jobTitle",
        name: "jobTitle",
        type: "text",
        validate: validate.validateJobTitle,
        icon: "icon-portfolio",
    },
    {
        label: "مهارت شغلی",
        id: "jobSkills",
        name: "jobSkills",
        type: "text",
        validate: validate.validateJobSkill,
        icon: "icon-skills",
    },
    {
        label: "نام و نام خانوادگی",
        id: "fullName",
        name: "fullName",
        type: "text",
        validate: validate.validateFullName,
        icon: "icon-user",
    },
    {
        label: "مرد",
        id: "0",
        name: "gender",
        type: "radio",
        description: "جنسیت",
        icon: "",
    },
    {
        label: "زن",
        id: "1",
        name: "gender",
        type: "radio",
        styleParent: "display: flex; flex-direction: row-reverse; align-items: center;",
        icon: "",
    },
    {
        label: "تحصیلات",
        id: "education",
        name: "education",
        type: "text",
        validate: validate.validateEducation,
        icon: "icon-open-book",
    },
    {
        label: "شماره همراه",
        id: "phone",
        name: "phone",
        type: "text",
        validate: validate.validatePhone,
        icon: "icon-phone",
    },
    {
        label: "ایمیل",
        id: "email",
        name: "email",
        type: "email",
        validate: validate.validateEmail,
        icon: "icon-email",
    },
]

export let accountNavInformations = [
    {
        id: "1",
        text: "داشبورد",
        link: "dashboard",
        className: "account-nav__item",
        icon: "icon-menu_1",
    },
    {
        id: "2",
        text: "پروفایل",
        link: "profile",
        className: "account-nav__item",
        icon: "icon-user",
    },
    {
        id: "3",
        text: "کارمندان",
        link: "list",
        className: "account-nav__item",
        icon: "icon-user",
    },
]

export default {
    inputSignupInformations,
    inputLoginInformations,
    inputProfileInformations,
    accountNavInformations,
}